datagovernance
configcat/.net-sdk pull request #14
Opened 2020-10-08 00:35 UTC by endret

2020-10-08 06:48 UTC, laliconfigcat requested changes

2020-10-09 15:07 UTC, endret commented on src/ConfigCatClient/HttpConfigFetcher.cs
> +            var newConfig = ProjectConfig.Empty;
I move up the assign

2020-10-09 15:09 UTC, endret commented on src/ConfigCatClient/HttpConfigFetcher.cs
> +                if (body?.Preferences != null)
fixed

2020-10-09 15:11 UTC, endret commented on src/ConfigCatClient/HttpConfigFetcher.cs
> +        private async Task<Tuple<HttpResponseMessage, string>> FetchRequest(ProjectConfig lastConfig, HttpRequestMessage request, sbyte maxExecutionCount = 3)
well, I passed the `uri` only and create the `HttpRequestMessage` in the method ;)

2020-10-09 15:16 UTC, laliconfigcat approved these changes

2020-10-12 11:05 UTC, merged