Sdk improvements
configcat/.net-sdk pull request #32
Opened 2022-02-18 16:05 UTC by z4kn4fein

### Describe the purpose of your pull request

Through this tiny little PR I did the following:
- **Introduced a new configuration API replacing the builder pattern**:

  ```cs
  ConfigCatClientBuilder
      .Initialize(SDKKEY)
      .WithLogger(consoleLogger)
      .WithAutoPoll()
          .WithMaxInitWaitTimeSeconds(5)
          .WithPollIntervalSeconds(60)
      .Create();
  ```
  
  Will look like this:
  ```cs
  new ConfigCatClient(options =>
  {
      options.SdkKey = SDKKEY;
      options.PollingMode = PollingModes.AutoPoll(TimeSpan.FromSeconds(60), TimeSpan.FromSeconds(5));
      options.Logger = consoleLogger;
  });
  ```
  
  The old API is still available it's just marked with the `  [Obsolete]` attribute.

- **Added `GetAllValues()` and `GetAllValuesAsync()`**:  
  These methods are now evaluating all feature flags and settings into an `IDictionary<string, object>`.

- **Added `FlagOverrides`**:  
  It's now possible to feed the SDK with local feature flag and setting values. 
  - **Dictionary**
    ```cs
    var dict = new Dictionary<string, object>
    {
        {"enabledFeature", true},
        {"intSetting", 5},
    };

    using var client = new ConfigCatClient(options =>
    {
        options.SdkKey = "localhost";
        options.FlagOverrides = FlagOverrides.LocalDictionary(dict, 
            OverrideBehaviour.LocalOnly);
    });
    ```
  - **File**
    ```cs
    using var client = new ConfigCatClient(options =>
    {
        options.SdkKey = "localhost";
        options.FlagOverrides = FlagOverrides.LocalFile("path/to/file", 
            autoReload: false, 
            overrideBehaviour: OverrideBehaviour.LocalOnly);
    });
    ```
  Three behaviours available: `LocalOnly`, `LocalOverRemote`, and `RemoteOverLocal`.
  With `LocalOnly` the SDK switches into a completely offline state, and only the override values are served.
  `LocalOverRemote` and `RemoteOverLocal` merge the local and remote feature flag values respecting one or another in case of key duplications.

- **Changes in JSON handling**:  
  In respect of #30 `System.Text.Json` is favored over `Newtonsoft.Json` in frameworks newer than `net45`. `System.Text.Json` is not available for `net45` so that target remains with `Newtonsoft.Json`.

- **Added `net5.0` and `net6.0` target frameworks**.

- **Applied a proposal solution for** #26.
  To prevent possible deadlocks the following changes were applied:
  - Created a synchronous extension for the existing fully async `IConfigCache`. In the future we will replace that interface with the new one (`IConfigCatCache`) that has now the sync API and inherits the async API from `IConfigCache`.  `IConfigCache` was marked with `[Obsolete]` to maintain backward compatibility. `InMemoryConfigCache` now implements both sync and async APIs through `IConfigCatCache`.
  - Extended the config services (`AutoPoll`, `LazyLoad`, `ManualPoll`) with synchronous branches that are using the new cache's sync / async methods in respect of sync and async customer calls.
  - Extended the `HttpConfigFetcher` with a synchronous `Fetch` that uses the `HttpClient`'s `Send()` method where it's available (`net5.0` and above). Below `net5.0` the synchronous path falls back to a functionality that queues the HTTP request to a thread pool thread and waits for its completion. This solution prevents deadlocks however, it puts more load on the thread pool.

- **CI Changes**:
  - Introduced new [GitHub actions for Linux and macOS builds](https://github.com/configcat/.net-sdk/actions/workflows/linux-macOS-CI.yml). 
  - The [sonarcloud analysis](https://github.com/configcat/.net-sdk/actions/workflows/sonar-analysis.yml) is moved to a separate Action from the appveyor task. 
  - Removed codecov completely, it will be replaced by the coverage data from sonarcloud.

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2022-02-21 16:58 UTC, laliconfigcat requested changes

2022-02-21 16:58 UTC, laliconfigcat commented on src/ConfigCatClient/ProjectConfig.cs
> +        public override bool Equals(object obj) => obj != null && obj is ProjectConfig config && this.Equals(config);
```suggestion
        public override bool Equals(object obj) => obj is ProjectConfig config && this.Equals(config);
```

2022-02-21 17:05 UTC, laliconfigcat approved these changes

2022-02-21 17:06 UTC, laliconfigcat commented
<3

2022-02-23 00:32 UTC, endret commented on src/ConfigCatClient/Cache/InMemoryConfigCache.cs
> -        private readonly ReaderWriterLockSlim lockSlim = new ReaderWriterLockSlim();
why did you eliminate the locking mechanism?

2022-02-23 11:20 UTC, z4kn4fein commented on src/ConfigCatClient/ConfigService/NullConfigService.cs
> +    internal sealed class NullConfigService : IConfigService
Done

2022-02-23 11:28 UTC, z4kn4fein commented on src/ConfigCatClient/HttpConfigFetcher.cs
> +                if (response is { IsSuccessStatusCode: true })
This pattern doesn't match when the response is null. The `FetchRequest` was changed to iterative and got a branch where it could return a null HTTP response.

2022-02-23 11:29 UTC, z4kn4fein commented on src/ConfigCatClient/HttpConfigFetcher.cs
> +            this.cancellationTokenSource.Cancel();
You are right, the `Dispose()` cancels all pending requests, but the cancellation token used to cancel not only the pending requests, but each subsequent content reads as well.

2022-02-23 11:34 UTC, z4kn4fein commented on src/ConfigCatClient/Override/LocalFileDataSource.cs
> +        private readonly TaskCompletionSource<bool> asyncInit = new();
My intention here was more like to wait for the file loaded at least first, the semaphore slim doesn't have the right semantics for that as it limits the simultaneous callers' number, but we can discuss if we want to have this data source work differently.

2022-02-23 11:38 UTC, z4kn4fein commented on src/ConfigCatClient/Cache/InMemoryConfigCache.cs
> -        private readonly ReaderWriterLockSlim lockSlim = new ReaderWriterLockSlim();
Yeah, I wanted to ask you about this but completely forgot it sorry. My first thought was that locking on simply the member access and write is kinda useless here, but now I realized that I missed the fact that the member is a struct and the lock protects the value copies. I added the locking back.

2022-02-23 11:46 UTC, z4kn4fein commented on src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
> +            Task.Run(async () =>
My intention was to remove the thread blocking wait and the possibility of spawning simultaneous fetches from overlapping Timer ticks.

2022-02-23 23:44 UTC, endret commented on src/ConfigCatClient/Cache/InMemoryConfigCache.cs
> -        private readonly ReaderWriterLockSlim lockSlim = new ReaderWriterLockSlim();
hmm...all the same, I felt a little uncertainty :D You attracted my attention that it is a struct and I'm thinking why it's not a static variable...but I guess we will have an other issue with static (when the users implement multiple clients with multiple SDK key it can be an issue). it's working for many years we'd leave it :)

2022-02-23 23:53 UTC, endret commented on src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
> +            Task.Run(async () =>
Ok, but I think it would be safer to put delay logic into `finally` block or before the business logic (RefreshConfigAsync) my concern is if the logic fails (any reason) it can flood.

2022-02-24 00:02 UTC, endret commented on src/ConfigCatClient/Override/LocalFileDataSource.cs
> +                using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
I think you should ensure some thread safe solution, you can create a FileStream with FileShare option which can be a solution or you can use any exclusive locking. (I can not trust FileWatcher and don't know how it works when it fires multiple times rapidly :) )

2022-02-24 00:05 UTC, endret commented on src/ConfigCatClient/HttpConfigFetcher.cs
> +            this.cancellationTokenSource.Cancel();
Ah got it! I missed, thanks!

2022-02-25 10:37 UTC, z4kn4fein commented on src/ConfigCatClient/ConfigService/AutoPollConfigService.cs
> +            Task.Run(async () =>
Yep, thanks for the suggestion, I added an extra try-catch and moved the delay to the inner's `finally` block.

2022-02-25 10:39 UTC, z4kn4fein commented on src/ConfigCatClient/Override/LocalFileDataSource.cs
> +                using var stream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
I feel you bro, I have added a gate check to prevent simultaneous file reads from frequently repeating requests.

2022-02-27 21:15 UTC, endret approved these changes
https://media.giphy.com/media/OE6FE4GZF78nm/giphy.gif

2022-03-03 12:34 UTC, merged