improves logging based the latest onboarding tests
configcat/.net-sdk pull request #38
Opened 2022-08-09 12:36 UTC by zoltan-david

### Describe the purpose of your pull request

- Rephrased the messages to help the onboarding users.
- Added color coding to the default console logger.

### Related issues (only if applicable)

no tickets yet

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2022-08-10 13:13 UTC, laliconfigcat commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                        logger.Log($"- rule eval: ['null' {EvaluateLogger<T>.FormatComparator(rule.Comparator)} '{rule.ComparisonValue}'] => no match");
```suggestion
                        logger.Log($"- rule evaluation: ['null' {EvaluateLogger<T>.FormatComparator(rule.Comparator)} '{rule.ComparisonValue}'] => no match");
```

2022-08-10 13:13 UTC, laliconfigcat commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                        logger.Log($"- rule eval: ['null' {EvaluateLogger<T>.FormatComparator(rule.Comparator)} '{rule.ComparisonValue}'] => no match");
```suggestion
                        logger.Log($"- rule evaluation: ['null' {EvaluateLogger<T>.FormatComparator(rule.Comparator)} '{rule.ComparisonValue}'] => no match");
```

2022-08-10 13:13 UTC, laliconfigcat commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                    string l = $"- rule eval: ['{comparisonAttributeValue}' {EvaluateLogger<T>.FormatComparator(rule.Comparator)} '{rule.ComparisonValue}'] => ";
```suggestion
                    string l = $"- rule evaluation: ['{comparisonAttributeValue}' {EvaluateLogger<T>.FormatComparator(rule.Comparator)} '{rule.ComparisonValue}'] => ";
```

2022-08-10 14:12 UTC, endret commented on src/ConfigCatClient/Logging/ConsoleLogger.cs
> +            var originalColor = Console.ForegroundColor;
this is not a thread-safe solution but I can live with it

2022-08-10 14:15 UTC, endret commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                    evaluateLog.Log($"- % options: evaluated to '{variation.Value}'.");
this message does not contain the `key`...is it intentional?

2022-08-11 09:48 UTC, zoltan-david commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                    evaluateLog.Log($"- % options: evaluated to '{variation.Value}'.");
yes, it is intentional
the key is visible in another part of the same message

![image](https://user-images.githubusercontent.com/54935463/184107578-1b69b7d6-9e8e-4d62-8db5-da65815b954c.png)

2022-08-11 09:49 UTC, zoltan-david commented on src/ConfigCatClient/Logging/ConsoleLogger.cs
> +            var originalColor = Console.ForegroundColor;
👍 I'll handle this, thanks

2022-08-11 10:06 UTC, endret approved these changes

2022-08-11 19:32 UTC, endret commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                    this.log.Warning($"Cannot evaluate targeting rules and % options for '{key}' (UserObject mising). You should pass a UserObject to GetValue() or GetValueAsync(), in order to make t
typo, `missing`

2022-08-11 19:36 UTC, endret commented on src/ConfigCatClient/Evaluate/RolloutEvaluator.cs
> +                evaluateLog.Log($"applying the % option that matches the User's pseudo-random: {hashScale} (this value is sticky and consitent across all SDKs)");
IMHO we should not write this value into log.

2022-08-11 19:53 UTC, endret requested changes
I dropped some comments. Please review them. Thanks

2022-08-11 19:54 UTC, endret commented on src/ConfigCatClient/Logging/ConsoleLogger.cs
> +        private object _lock = new object();
this could be `readonly` and `static` too.

2022-08-12 22:31 UTC, z4kn4fein commented on src/ConfigCatClient/Logging/ConsoleLogger.cs
> +            const string defaultColorCode = "\u001B[36m";
ANSI codes are not supported prior to win10 v1511 and has to be explicitly enabled on the output console, i.e. it's not safe to use them in a library, where you can't be sure the host has that feature. Otherwise, only the raw char sequence will be displayed.
I'd recommend to remove the coloring completely.

2022-09-05 12:39 UTC, laliconfigcat approved these changes

2022-09-05 12:43 UTC, sigewuzhere approved these changes

2022-09-05 22:37 UTC, endret approved these changes

2022-09-06 12:58 UTC, merged