LazyLoad and AutoPoll refresh logic improvements
configcat/.net-sdk pull request #47
Opened 2022-10-14 17:24 UTC by adams85

### Describe the purpose of your pull request

* Improves refresh logic of `AutoPollConfigService` and `LazyLoadConfigService` to take the cache download time into account to fetch the config only if cached config is unavailable or stale.
* Also does some cleanup around `*ConfigService` classes.

Breaking changes:
* Changes `ProjectConfig` to reference type with value equality (record)
* Slightly changes the behavior of `ProjectConfig.TimeStamp` (only updated when download succeeds)

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [x] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2022-10-18 14:11 UTC, z4kn4fein commented on src/ConfigCatClient/IsExternalInit.cs
> +    internal static class IsExternalInit
Could you please explain the reason for this?

2022-10-18 18:45 UTC, adams85 commented on src/ConfigCatClient/IsExternalInit.cs
> +    internal static class IsExternalInit
This class is [necessary to enable C# 9 records (more precisely, init-only setters) in older runtimes](https://btburnett.com/csharp/2020/12/11/csharp-9-records-and-init-only-setters-without-dotnet5.html#creating-init-only-properties-on-older-frameworks).

2022-10-18 19:24 UTC, adams85 commented on src/ConfigCatClient/IsExternalInit.cs
> +    internal static class IsExternalInit
On a second thought it's maybe not the best idea to use init-only setters after all:

> To use a public or protected property with an init only setter, the consumer must be using a C# compiler that supports C# 9. Even if they aren’t using LangVersion 9 in their csproj, the compiler must be capable of understanding the modreq. If the consumer doesn’t understand the init only setter, it will be unable to access the setter at all and will appear as a read-only property.
> 
> Similarly, other languages like VB.NET don’t like init only setters. In fact, VB.NET won’t recognize the property at all, even as read-only, and even with the latest version of the VB.NET compiler.

Luckily, records are not so problematic. They are just plain classes with a bunch of auto-generated code under the hood. The worst that can happen is that end users can't use the generated clone method in their code. (For more details, see [this section](https://btburnett.com/csharp/2020/12/11/csharp-9-records-and-init-only-setters-without-dotnet5.html#public-records).)

So, using records seems fine but I'm not sure about init-only setters. Although it's stated in [the specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/init#modreqs-vs-attributes) that VB.NET and F# compilers are also updated to support this feature, probably we should aim for better backward compatibility. What's your opinion on this?

2022-10-19 12:36 UTC, z4kn4fein commented on src/ConfigCatClient/IsExternalInit.cs
> +    internal static class IsExternalInit
I agree, we should be as backward compatible as we can; let's just try to live without init setters for the next couple of compiler versions. 😄

2022-10-22 22:15 UTC, endret requested changes

2022-10-22 22:15 UTC, endret commented on src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
> +            if (!latestConfig.Equals(newConfig) && !newConfig.Equals(ProjectConfig.Empty))
Based on this condition, it won't update the cache. It means the timestamp value is still the original value (first acquire timestamp). Some modes (Lazy, Manual) all times have to update it!

2022-10-24 12:15 UTC, adams85 commented on src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
> +            if (!latestConfig.Equals(newConfig) && !newConfig.Equals(ProjectConfig.Empty))
Indeed, this check prevents updating the cache when [only the timestamp is modified (that is, the CDN server has returned `304 Not Modified`)](https://github.com/configcat/.net-sdk/pull/47/files#diff-604a59921cc2d4a266f0a09c7c1447641770775fd84ccc80c6ff655f5e1994e4R99-R102) because [timestamp is not included the equality check of `ProjectConfig`](https://github.com/configcat/.net-sdk/pull/47/files#diff-7e7a10086d9be83a8d2b3928c525c2d07f3b44cbb3836542f37d2be3be1aa1f5R91-R94). Is this what you mean?

How about changing the condition to something like this: `if (newConfig.TimeStamp > latestConfig.TimeStamp && !newConfig.Equals(ProjectConfig.Empty))`? (`TimeStamp` uses UTC, so daylight saving time wouldn't be an issue).

However, as far as I can see, all the polling modes should use this condition. Even auto polling because [the timestamp is now used by its refresh logic](https://github.com/configcat/.net-sdk/pull/47/files#diff-03008813bfbb785c25a18f37d2a20a6330fb8b46e78261d6e3b1a7b2b2e169e7R150). Is my understanding correct?

2022-10-24 20:55 UTC, endret commented on src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
> +            if (!latestConfig.Equals(newConfig) && !newConfig.Equals(ProjectConfig.Empty))
> Indeed, this check prevents updating the cache when [only the timestamp is modified (that is, the CDN server has returned `304 Not Modified`)](https://github.com/configcat/.net-sdk/pull/47/files#diff-604a59921cc2d4a266f0a09c7c1447641770775fd84ccc80c6ff655f5e1994e4R99-R102) because [timestamp is not included the equality check of `ProjectConfig`](https://github.com/configcat/.net-sdk/pull/47/files#diff-7e7a10086d9be83a8d2b3928c525c2d07f3b44cbb3836542f37d2be3be1aa1f5R91-R94). Is this what you mean?

Yes, it is and it is intentional.

> 
> How about changing the condition to something like this: `if (newConfig.TimeStamp > latestConfig.TimeStamp && !newConfig.Equals(ProjectConfig.Empty))`? (`TimeStamp` uses UTC, so daylight saving time wouldn't be an issue).
> 

You should not do or circumspectly implement any changes around this logic, for example, Equals can make a decision about whether it is changed or not (The SDK has logic behind this, like OnChange event). In my mind, the TimeStamp value in the ProjectConfig is the config acquisition time and not the last (trying) fetch. It should update only if the customer invokes force refresh or if the configService has a business logic for that (e.g. Lazy load can force the refresh)

> However, as far as I can see, all the polling modes should use this condition. Even auto polling because [the timestamp is now used by its refresh logic](https://github.com/configcat/.net-sdk/pull/47/files#diff-03008813bfbb785c25a18f37d2a20a6330fb8b46e78261d6e3b1a7b2b2e169e7R150). Is my understanding correct?

Yep the TS is not persisting at all times, you have to proceed very circumspectly and with sensitivity if you are planning to build a business logic with it.

2022-10-24 21:58 UTC, adams85 commented on src/ConfigCatClient/ConfigService/ConfigServiceBase.cs
> +            if (!latestConfig.Equals(newConfig) && !newConfig.Equals(ProjectConfig.Empty))
> In my mind, the TimeStamp value in the ProjectConfig is the config acquisition time and not the last (trying) fetch. It should update only if the customer invokes force refresh or if the configService has a business logic for that (e.g. Lazy load can force the refresh)

Prior to this PR, `ProjectConfig.TimeStamp` *was* the time of last fetch attempt. I changed this behavior [here](https://github.com/configcat/.net-sdk/pull/47/files#diff-604a59921cc2d4a266f0a09c7c1447641770775fd84ccc80c6ff655f5e1994e4L126-L127) because I also think that it should be the last acquisition (i.e. last successful download) time. Increasing the timestamp when download fails makes no sense because we can't decide whether our cached config is still up-to-date or not.

I suggested changing the condition to `if (newConfig.TimeStamp > latestConfig.TimeStamp && !newConfig.Equals(ProjectConfig.Empty))` because when download succeeds (by returning either a new config or a 304 status code), acquisition time (`TimeStamp`) needs to be updated in the cache so that expiration checks yield the correct result. (The problem with `!latestConfig.Equals(newConfig)` is that `ProjectConfig.Equals` ignores `TimeStamp`. Although this behavior is somewhat unintuitive, I didn't change it to not introduce breaking changes unnecessarily.)

However, it's true that changing the condition is not enough. The OnChange event should be raised only when the fetched config is actually changed.

2022-10-25 00:07 UTC, endret commented on src/ConfigCatClient/HttpConfigFetcher.cs
>                          case HttpStatusCode.NotFound:
As we discussed consider setting TS value as well to prevent flooding.

2022-10-25 09:24 UTC, endret approved these changes

2022-10-25 11:53 UTC, merged