Config v6
configcat/.net-sdk pull request #75
Opened 2023-06-24 13:58 UTC by adams85

### Describe the purpose of your pull request

Config v6 support:
- AND conditions
- Percentage options in targeting rules
- New condition types
  - Prerequisite Flag Condition
  - Segment Condition
- New operators

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [ ] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2023-08-18 15:34 UTC, adams85 commented on src/ConfigCatClient/Evaluation/RolloutEvaluator.cs
> +            logBuilder.IncreaseIndent();
You're right that this approach goes against clean the single responsibility principle, however in this specific case there are other factors to consider:

1. Maintainability. If we wanted to decouple the logging logic from the flag evaluation logic, we'd need to build an object graph during evaluation which would describe the process of evaluation. To be able to do this, firstly, we'd need to define a data model for the evaluation log. However, the evaluation log gets pretty complex in config v6 (for a glimpse of complexity, see this [test case](https://github.com/configcat/.net-sdk/blob/cd4b022264ed97f57d6994fc85c425d4e59bb5a7/src/ConfigCat.Client.Tests/data/evaluationlog/prerequisite_flag/prerequisite_flag.txt)). That is, that data model would be pretty big as well. Secondly, after the evaluation we'd need to traverse the object graph and build the info log text. We'd also need to implement this traversal logic, which would overlap with the evaluation logic to a great extent. In other words, we'd need to additionally write a bunch of redundant code. In previous code reviews it was pointed out multiple times that we should keep our implementation as slim and simple as possible. Introducing an additional data model and logic for evaluation logging would go against this directive.

2. Performance. Of course, this aspect is not as important as the previous one but this is a library and, as such, it should aim to have good performance to consume the least amount of end users' resources possible. After all, CPU time costs money, which means that good performance saves money for end users (and, while we're at it, reduces CO2 emission for all of us...:) I'm pretty sure that the "clean code" approach would result in worse performance as we'd need to allocate an object graph during evaluation and do an extra traversal step afterwards.

This is why I chose this approach and still think it's the better solution overall. (BTW, logging was implemented in the Python SDK in the same spirit.)

If I'm missing something or you have an idea how to tackle the points above using a cleaner solution, please describe what design you have in mind.

2023-08-18 15:37 UTC, adams85 commented
Some benchmark results to support the arguments made for the current implementation.

|               Method |            Runtime | LogInfo |     Mean |     Error |   StdDev | Ratio | RatioSD |       Gen0 |     Gen1 | Allocated | Alloc Ratio |
|--------------------- |------------------- |-------- |---------:|----------:|---------:|------:|--------:|-----------:|---------:|----------:|------------:|
| MatrixTests_ConfigV5 |           .NET 6.0 |   False | 25.92 ms |  2.274 ms | 0.125 ms |  1.00 |    0.00 |  2406.2500 |        - |  38.88 MB |        1.00 |
| MatrixTests_ConfigV5 | .NET Framework 4.8 |   False | 56.24 ms | 16.932 ms | 0.928 ms |  2.17 |    0.05 |  7111.1111 |        - |  43.08 MB |        1.11 |
|                      |                    |         |          |           |          |       |         |            |          |           |             |
| MatrixTests_ConfigV6 |           .NET 6.0 |   False | 11.17 ms |  2.751 ms | 0.151 ms |  1.00 |    0.00 |   859.3750 |        - |  13.94 MB |        1.00 |
| MatrixTests_ConfigV6 | .NET Framework 4.8 |   False | 29.70 ms |  4.885 ms | 0.268 ms |  2.66 |    0.01 |  3218.7500 |        - |  19.36 MB |        1.39 |
|                      |                    |         |          |           |          |       |         |            |          |           |             |
| MatrixTests_ConfigV5 |           .NET 6.0 |    True | 25.64 ms |  3.050 ms | 0.167 ms |  1.00 |    0.00 |  2406.2500 |        - |  38.88 MB |        1.00 |
| MatrixTests_ConfigV5 | .NET Framework 4.8 |    True | 56.09 ms |  1.123 ms | 0.062 ms |  2.19 |    0.02 |  7111.1111 |        - |  43.08 MB |        1.11 |
|                      |                    |         |          |           |          |       |         |            |          |           |             |
| MatrixTests_ConfigV6 |           .NET 6.0 |    True | 28.51 ms |  0.423 ms | 0.023 ms |  1.00 |    0.00 |  3937.5000 |  31.2500 |  62.83 MB |        1.00 |
| MatrixTests_ConfigV6 | .NET Framework 4.8 |    True | 69.74 ms |  9.644 ms | 0.529 ms |  2.45 |    0.02 | 12875.0000 | 125.0000 |   77.4 MB |        1.23 |

2023-08-30 10:57 UTC, kp-cat commented on src/ConfigCatClient/Evaluation/EvaluateLogHelper.cs
> +                string.Format(CultureInfo.InvariantCulture, " ... <{0} more {1}>", count, count == 1 ? valueText : valuesText));
If I remember right for list we would like to use `()`
```suggestion
                string.Format(CultureInfo.InvariantCulture, " ... ({0} more {1})", count, count == 1 ? valueText : valuesText));
```

2023-09-01 09:25 UTC, adams85 commented on src/ConfigCatClient/Evaluation/RolloutEvaluator.cs
> +            logBuilder.IncreaseIndent();
After discussing the issue, we came to the conclusion that in this specific case the original approach is preferable.

2023-09-11 15:09 UTC, adams85 commented
@configcat/ux-qa-team May I also request a review from UX perspective for this PR? More specifically, for the XML comments of the source files located under `src/ConfigCatClient/Models`.

2023-09-13 14:20 UTC, sigewuzhere commented
Thanks, seems like this is pretty big, adding it to the UX board and will prioritize tomorrow morning.

2023-10-04 13:46 UTC, z4kn4fein requested changes

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/TargetingRule.cs
> +/// Targeting rule.
```suggestion
/// Describes a targeting rule.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/TargetingRule.cs
> +    /// The list of conditions (where there is a logical AND relation between the items).
```suggestion
    /// The list of conditions that are combined with the AND logical operator.
    /// It can be one of the following:
    /// - User condition
    /// - Segment condition
    /// - Prerequisite flag condition
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +/// User condition operator.
```suggestion
/// The comparison operator the evaluation process must use when it compares the given user attribute's value with the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// CONTAINS ANY OF - Does the comparison attribute contain any of the comparison values as a substring?
```suggestion
    /// CONTAINS ANY OF - It matches when the comparison attribute contains any comparison values as a substring.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// NOT CONTAINS ANY OF - Does the comparison attribute not contain any of the comparison values as a substring?
```suggestion
    /// NOT CONTAINS ANY OF - It matches when the comparison attribute does not contain any comparison values as a substring.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// IS ONE OF (semver) - Is the comparison attribute interpreted as a semantic version equal to any of the comparison values?
```suggestion
    /// IS ONE OF (semver) - It matches when the comparison attribute interpreted as a semantic version is equal to any of the comparison values.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// IS NOT ONE OF (semver) - Is the comparison attribute interpreted as a semantic version not equal to any of the comparison values?
```suggestion
    /// IS NOT ONE OF (semver) - It matches when the comparison attribute interpreted as a semantic version is not equal to any of the comparison values.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &lt; (semver) - Is the comparison attribute interpreted as a semantic version less than the comparison value?
```suggestion
    /// &lt; (semver) - It matches when the comparison attribute interpreted as a semantic version is less than the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &lt;= (semver) - Is the comparison attribute interpreted as a semantic version less than or equal to the comparison value?
```suggestion
    /// &lt;= (semver) - It matches when the comparison attribute interpreted as a semantic version is less than or equal to the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &gt; (semver) - Is the comparison attribute interpreted as a semantic version greater than the comparison value?
```suggestion
    /// &gt; (semver) - It matches when the comparison attribute interpreted as a semantic version is greater than the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &gt;= (semver) - Is the comparison attribute interpreted as a semantic version greater than or equal to the comparison value?
```suggestion
    /// &gt;= (semver) - It matches when the comparison attribute interpreted as a semantic version is greater than or equal to the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// = (number) - Is the comparison attribute interpreted as a decimal number equal to the comparison value?
```suggestion
    /// = (number) - It matches when the comparison attribute interpreted as a decimal number is equal to the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// != (number) - Is the comparison attribute interpreted as a decimal number not equal to the comparison value?
```suggestion
    /// != (number) - It matches when the comparison attribute interpreted as a decimal number is not equal to the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &lt; (number)  - Is the comparison attribute interpreted as a decimal number less than the comparison value?
```suggestion
    /// &lt; (number)  - It matches when the comparison attribute interpreted as a decimal number is less than the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &lt;= (number) - Is the comparison attribute interpreted as a decimal number less than or equal to the comparison value?
```suggestion
    /// &lt;= (number) - It matches when the comparison attribute interpreted as a decimal number is less than or equal to the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &gt; (number) - Is the comparison attribute interpreted as a decimal number greater than the comparison value?
```suggestion
    /// &gt; (number) - It matches when the comparison attribute interpreted as a decimal number is greater than the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// &gt;= (number) - Is the comparison attribute interpreted as a decimal number greater than or equal to the comparison value?
```suggestion
    /// &gt;= (number) - It matches when the comparison attribute interpreted as a decimal number is greater than or equal to the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// IS ONE OF (hashed) - Is the comparison attribute equal to any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// IS ONE OF (hashed) - It matches when the comparison attribute is equal to any of the comparison values (where the comparison is performed using the SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// IS NOT ONE OF (hashed) - Is the comparison attribute not equal to any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// IS NOT ONE OF (hashed) - It matches when the comparison attribute is not equal to any of the comparison values (where the comparison is performed using the SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// BEFORE (UTC datetime) - Is the comparison attribute interpreted as the seconds elapsed since <see href="https://en.wikipedia.org/wiki/Unix_time">Unix Epoch</see> less than the comparison valu
```suggestion
    /// BEFORE (UTC datetime) - It matches when the comparison attribute interpreted as the seconds elapsed since <see href="https://en.wikipedia.org/wiki/Unix_time">Unix Epoch</see> is less than the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// AFTER (UTC datetime) - Is the comparison attribute interpreted as the seconds elapsed since <see href="https://en.wikipedia.org/wiki/Unix_time">Unix Epoch</see> greater than the comparison va
```suggestion
    /// AFTER (UTC datetime) - It matches when the comparison attribute interpreted as the seconds elapsed since <see href="https://en.wikipedia.org/wiki/Unix_time">Unix Epoch</see> is greater than the comparison value.
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// EQUALS (hashed) - Is the comparison attribute equal to the comparison value (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// EQUALS (hashed) - It matches when the comparison attribute is equal to the comparison value (where the comparison is performed using the SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// NOT EQUALS (hashed) - Is the comparison attribute not equal to the comparison value (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// NOT EQUALS (hashed) - It matches when the comparison attribute is not equal to the comparison value (where the comparison is performed using the SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// STARTS WITH ANY OF (hashed) - Does the comparison attribute start with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// STARTS WITH ANY OF (hashed) - It matches when the comparison attribute starts with any of the comparison values (where the comparison is performed using the SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// NOT STARTS WITH ANY OF (hashed) - Does the comparison attribute not start with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// NOT STARTS WITH ANY OF (hashed) - It matches when the comparison attribute does not start with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// ENDS WITH ANY OF (hashed) - Does the comparison attribute end with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// ENDS WITH ANY OF (hashed) - It matches when the comparison attribute ends with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// NOT ENDS WITH ANY OF (hashed) - Does the comparison attribute not end with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values)?
```suggestion
    /// NOT ENDS WITH ANY OF (hashed) - It matches when the comparison attribute does not end with any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserComparator.cs
> +    /// ARRAY NOT CONTAINS ANY OF (hashed) - Does the comparison attribute interpreted as a comma-separated list not contain any of the comparison values (where the comparison is performed using the
```suggestion
    /// ARRAY NOT CONTAINS ANY OF (hashed) - It matches when the comparison attribute interpreted as a comma-separated list does not contain any of the comparison values (where the comparison is performed using the salted SHA256 hashes of the values).
```

2023-10-04 13:46 UTC, z4kn4fein commented on src/ConfigCatClient/Models/UserCondition.cs
> +    /// The value that the attribute is compared to. Can be a value of the following types: <see cref="string"/> (including a semantic version), <see cref="double"/> or <see langword="IReadOnlyList{T
```suggestion
    /// The value that the User Object's attribute is compared to. Can be a value of the following types: <see cref="string"/> (including a semantic version), <see cref="double"/> or <see langword="IReadOnlyList{T}" />, where T is <see cref="string"/>.
```

2023-10-04 15:35 UTC, adams85 commented on src/ConfigCatClient/Models/Condition.cs
> +/// Base interface for conditions.
Will need to do add some formatting (e.g. add `<br/>`s) otherwise the comment will appear as a continuous text block in Intellisense.

2023-10-04 15:37 UTC, adams85 commented on src/ConfigCatClient/Models/Condition.cs
> +/// Base interface for conditions.
Also, `the user conditions that are combined...` should probably be just `the conditions that are combined` since user condition is one of the actual condition types.

2023-10-04 15:44 UTC, adams85 commented on src/ConfigCatClient/Models/SegmentComparator.cs
> +/// Segment condition operator.
The `The` at the beginning seems unnecessary and not consistent with e.g. `PrerequisiteFlagComparator` either.

2023-10-04 15:46 UTC, adams85 commented on src/ConfigCatClient/Models/TargetingRule.cs
> +    /// The list of conditions (where there is a logical AND relation between the items).
Same formatting issue as in the case of https://github.com/configcat/.net-sdk/pull/75#discussion_r1345729800

2023-10-04 15:50 UTC, adams85 commented on src/ConfigCatClient/Models/UserComparator.cs
> +/// User condition operator.
`User Object attribute comparison operator used during the evaluation process.` might be more succint and more consistent with the other comparator types' documentation.

2023-10-04 15:53 UTC, adams85 commented on src/ConfigCatClient/Models/UserCondition.cs
> +/// User condition.
I suggest `based on User Object attributes` for more clarity and consistency.

2023-10-04 15:54 UTC, adams85 commented on src/ConfigCatClient/Models/UserCondition.cs
> +    /// The value that the attribute is compared to. Can be a value of the following types: <see cref="string"/> (including a semantic version), <see cref="double"/> or <see langword="IReadOnlyList{T
I suggest `User Object attribute` for consistency.

2023-10-04 15:58 UTC, adams85 commented on src/ConfigCatClient/Models/Config.cs
> +/// ConfigCat config.
I suggest `Details of a ConfigCat config` for more clarity. Also, `config` is not written in upper case anywhere else in the XML docs.

2023-10-04 15:59 UTC, adams85 commented on src/ConfigCatClient/Models/Segment.cs
> +/// Segment.
I suggest lowercase for consistency. `Segment` is not written in upper case anywhere else in the XML docs.

2023-10-26 10:21 UTC, laliconfigcat requested changes
OMG! Good job!

2023-10-27 07:56 UTC, adams85 commented on src/ConfigCatClient/Evaluation/RolloutEvaluator.cs
> +                throw new InvalidOperationException("Targeting rule THEN part is missing or invalid.");
When designing the config json-related validation and error handling, we decided that we'd use the following rule of thumb:

If the config json is invalid (i.e. doesn't match the schema), we interrupt the evaluation and report the error because it's very likely that the evaluation won't lead to the expected result anyway.

We decided on this solution because the config json shouldn't contain have invalid data in the first place (since most of the time it's generated by our well-tested backend logic). If it's still invalid, we probably have a serious issue and we shouldn't let that slip.

2023-10-27 07:59 UTC, adams85 commented on src/ConfigCat.Client.Tests/ConfigV5EvaluationTests.cs
> +public class ConfigV5EvaluationTests : EvaluationTestsBase
You're right, gonna fix this. (If only we had some more distinctive words for these two things... 😄)

2023-11-02 12:37 UTC, laliconfigcat approved these changes
![hero-cat-only](https://github.com/configcat/.net-sdk/assets/63732287/87680ebe-0b7a-4c0b-8125-5c3b1a7a0b5a)

2023-11-06 01:17 UTC, endret reviewed
it would be nice to ensure some explicit unit tests for new utils functions.

2023-11-06 07:50 UTC, adams85 commented on src/ConfigCatClient/Evaluation/RolloutEvaluator.cs
> +        var hashValue =
No doubt it was more readable. However, it was pretty inefficient performance-wise too. The original version
1. converts the hash byte array to a hex strings (allocates a new string object)
2. takes a substring of that string (another allocation)
3. re-parses the substring

The new version avoids all these steps, so I think, in library code this one is preferable and together with the comment the readability should be good enough.

2023-11-13 00:32 UTC, endret approved these changes

2023-11-15 10:48 UTC, z4kn4fein approved these changes

2023-11-20 12:50 UTC, kp-cat commented on src/ConfigCatClient/Evaluation/RolloutEvaluator.cs
> +        error = HandleInvalidUserAttribute(condition, key, attributeName, $"'{attributeValue}' is not a valid string array");
```suggestion
        error = HandleInvalidUserAttribute(condition, key, attributeName, $"'{attributeValue}' is not a valid JSON string array");
```

2023-11-20 23:47 UTC, kp-cat approved these changes

2023-11-21 07:41 UTC, kp-cat commented on src/ConfigCatClient/User.cs
> +    /// Some of the comparison types work with other types of values, as descibed below.
```suggestion
    /// Some of the comparison types work with other types of values, as described below.
```

2023-11-21 07:43 UTC, merged

2023-11-21 07:48 UTC, adams85 commented on src/ConfigCatClient/User.cs
> +    /// Some of the comparison types work with other types of values, as descibed below.
Oops, I just noticed this after merging. I'll fix this in another PR.