Custom log filtering
configcat/.net-sdk pull request #95
Opened 2024-07-30 17:49 UTC by adams85

### Describe the purpose of your pull request

Adds a new, more convenient way  (`ConfigCatClientOptions.LogFilter`) for consumers to specify custom log event filter logic.

Also, brings some performance improvements around log messages (reduced memory allocation).

### Related issues (only if applicable)

https://trello.com/c/IxCFbq2j

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [ ] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2024-07-30 19:41 UTC, endret requested changes

2024-07-30 19:41 UTC, endret commented on src/ConfigCatClient/Utils/LazyString.cs
> +internal struct LazyString
Consider to reuse the `Lazy<String>` type...with this could have less custom implementation.

2024-07-30 20:19 UTC, adams85 commented on src/ConfigCatClient/Utils/LazyString.cs
> +internal struct LazyString
Thanks for the tip but unfortunately `Lazy<string>` would defeat the purpose of the PR because it would involve multiple heap allocations:

First of all, `Lazy<T>` is a reference type. In addition, it takes a factory of type `Func<T>`, which would mean two more allocations since the factory would need to close over the format string and the arguments and in C# closures are stored in an instance of a compiler generated class, plus an instance of `MulticastDelegate` targeting this instance should be created as well.

2024-08-01 20:46 UTC, endret requested changes

2024-08-01 20:46 UTC, endret commented on src/ConfigCatClient/Utils/LazyString.cs
> +    public string? Value => this.argsOrValue as string;
I see that it is an internal util, but based on the way the built-in Lazy class works, your implementation may be deceptive because the `Value` property could serve a false value if the consumer does not call the `.ToString()` method.

2024-08-01 20:46 UTC, endret commented on src/ConfigCatClient/Utils/LazyString.cs
> +internal struct LazyString
Ah...I'm seeing the requirements from the trello card. :)

2024-08-01 20:47 UTC, endret requested changes

2024-08-01 20:47 UTC, endret commented on src/ConfigCatClient/Utils/LazyString.cs
> +internal struct LazyString
It would be nice to have some unit tests for this internal util.

2024-08-02 17:39 UTC, adams85 commented on src/ConfigCatClient/Utils/LazyString.cs
> +    public string? Value => this.argsOrValue as string;
Originally, I had no intention to implement some slimmed down version of `Lazy<T>`, just couldn't come up with a better name. :)

But you're right that if it's named that way, it would be better to make its API similar to `Lazy<T>`. So I made some changes to the `Value` property to have similar semantics to `Lazy<T>`.Value.

2024-08-02 18:13 UTC, endret approved these changes

2024-08-02 18:13 UTC, endret commented on src/ConfigCatClient/Utils/LazyString.cs
> +    public override string ToString() => Value ?? string.Empty;
<3

2024-08-21 07:26 UTC, merged